
export const FETCH_MENU = 'FETCH_MENU';
export const FETCH_MENU_SUCCESS = 'FETCH_MENU_SUCCESS';
export const FETCH_MENU_FAILURE = 'FETCH_MENU_FAILURE';

export const ADD_MEAL = 'ADD_MEAL';
export const ADD_MEAL_SUCCESS = 'ADD_MEAL_SUCCESS';
export const ADD_MEAL_FAILURE = 'ADD_MEAL_FAILURE';

export const EDIT_MEAL = 'EDIT_MEAL';
export const EDIT_MEAL_SUCCESS = 'EDIT_MEAL_SUCCESS';
export const EDIT_MEAL_FAILURE = 'EDIT_MEAL_FAILURE';

export const DELETE_MEAL = 'DELETE_MEAL';
export const DELETE_MEAL_SUCCESS = 'DELETE_MEAL_SUCCESS';
export const DELETE_MEAL_FAILURE = 'DELETE_MEAL_FAILURE';

export const FETCH_PENDING_ORDERS = 'FETCH_PENDING_ORDERS';
export const FETCH_PENDING_ORDERS_SUCCESS = 'FETCH_PENDING_ORDERS_SUCCESS';
export const FETCH_PENDING_ORDERS_FAILURE = 'FETCH_PENDING_ORDERS_FAILURE';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const LOGOUT_USER = 'LOGOUT_USER';

export const FETCH_ORDERS = 'FETCH_ORDERS';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILURE = 'FETCH_ORDERS_FAILURE';

export const FETCH_HIGHLIGHTS = 'FETCH_HIGHLIGHTS';
export const FETCH_HIGHLIGHTS_SUCCESS = 'FETCH_HIGHLIGHTS_SUCCESS';
export const FETCH_HIGHLIGHTS_FAILURE = 'FETCH_HIGHLIGHTS_FAILURE';

export const FETCH_STAFF = 'FETCH_STAFF';
export const FETCH_STAFF_SUCCESS = 'FETCH_STAFF_SUCCESS';
export const FETCH_STAFF_FAILURE = 'FETCH_STAFF_FAILURE';

export const ADD_STAFF = 'ADD_STAFF';
export const ADD_STAFF_SUCCESS = 'ADD_STAFF_SUCCESS';
export const ADD_STAFF_FAILURE = 'ADD_STAFF_FAILURE';

export const REMOVE_STAFF = 'REMOVE_STAFF';
export const REMOVE_STAFF_SUCCESS = 'REMOVE_STAFF_SUCCESS';
export const REMOVE_STAFF_FAILURE = 'REMOVE_STAFF_FAILURE';